version: '3.1'

services:
  mysql:
     container_name: mysql-4write
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
     ports:
       - "3306:3306"
     restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-4write
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  registry:
    image: registry:latest
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/data:/var/lib/registry
    restart: unless-stopped
